  <br>
&nbsp;
-  assembled every Sunday in automated and untested manner, 
-  compiled using official Armbian build framework and digitally signed,
-  getting updates from official armbian servers almost every day,
-  assembled from unstable Debian and Ubuntu packages,
-  If you don't find image you are looking for, check <a href=https://www.armbian.com/download/ target=_blanks>supported builds</a>, <a href=https://archive.armbian.com target=_blank>archives</a> or <a href=https://github.com/armbian/build>build from sources</a>,
-  Armbian project maintainers <b>does not answer</b> any <b>support questions</b> regarding those builds!
-  Support? Check <a href=https://docs.armbian.com/User-Guide_Getting-Started/>general install instructions</a> or <a href=https://forum.armbian.com/forum/189-faq/>TV box specific</a>
  <br>
&nbsp;
