<p align="center">
  <a href="#">
  <img src="https://raw.githubusercontent.com/armbian/build/master/.github/armbian-logo.png" alt="Armbian logo" width="144">
  </a><br>
  <strong>Armbian Linux Community</strong><br>rolling release<br>
<br>
<a href=https://github.com/armbian/community><img alt="Armbian Linux rolling" src="https://img.shields.io/badge/dynamic/json?label=Armbian%20Linux%20edge&query=EDGE&color=34be5b&cacheSeconds=600&style=for-the-badge&url=https%3A%2F%2Fgithub.com%2Farmbian%2Fscripts%2Freleases%2Fdownload%2Fstatus%2Frunners_capacity.json"></a>
<br><br>
<br><br>
Build Clusters Health<br>
<a href="#"><img alt="GitHub Workflow Status" src="https://img.shields.io/github/actions/workflow/status/armbian-alpha/os/build.yml?label=01&style=flat-square&branch=main"></a>
<a href="#"><img alt="GitHub Workflow Status" src="https://img.shields.io/github/actions/workflow/status/armbian-beta/os/build.yml?label=02&style=flat-square&branch=main"></a>
<a href="#"><img alt="GitHub Workflow Status" src="https://img.shields.io/github/actions/workflow/status/armbian-gama/os/build.yml?label=03&style=flat-square&branch=main"></a>
<a href="#"><img alt="GitHub Workflow Status" src="https://img.shields.io/github/actions/workflow/status/armbian-delta/os/build.yml?label=04&style=flat-square&branch=main"></a>
<a href="#"><img alt="GitHub Workflow Status" src="https://img.shields.io/github/actions/workflow/status/armbiankappa/os/build.yml?label=05&style=flat-square&branch=main"></a>
<a href="#"><img alt="GitHub Workflow Status" src="https://img.shields.io/github/actions/workflow/status/armbianro/os/build.yml?label=06&style=flat-square&branch=main"></a>
<p>
<b>assembled once per day</b>
<br><br><a href=https://www.armbian.com/><img src="https://img.shields.io/badge/interested%20in%20stable%20images%3F-red?style=for-the-badge"></a><br><br>
<a href=https://fosstodon.org/@armbian><img alt="Mastodon Follow" src="https://img.shields.io/mastodon/follow/109365956768424870?domain=https%3A%2F%2Ffosstodon.org&logo=mastodon&style=flat-square"></a>
<a href=https://forum.armbian.com/forum/97-unmaintained-csceoltvb-other/><img src="https://img.shields.io/badge/support-forum-green?logo=googlechat&style=flat-square"></a>
<a href=https://liberapay.com/armbian><img alt="Liberapay patrons" src="https://img.shields.io/liberapay/patrons/armbian?logo=liberapay&style=flat-square"></a>
</p>
  <br>
&nbsp;

-  assembled once per day in automated and untested manner, 
-  compiled using official Armbian build framework and digitally signed,
-  getting updates from official armbian servers almost every day,
-  assembled from unstable Debian and Ubuntu packages,
-  If you don't find image you are looking for, check <a href=https://www.armbian.com/download/ target=_blanks>supported builds</a>, <a href=https://archive.armbian.com target=_blank>archives</a> or <a href=https://github.com/armbian/build>build from sources</a>,
-  Armbian project maintainers <b>does not answer</b> any <b>support questions</b> regarding those builds!
-  Support? Check <a href=https://docs.armbian.com/User-Guide_Getting-Started/>general install instructions</a> or <a href=https://forum.armbian.com/forum/189-faq/>TV box specific</a>
  <br>
&nbsp;
<p>
F.A.Q.
<ul>
  <li>What are Lunar and Sid? Lunar release is assembled from Ubuntu packages and Sid from Debian. Both have pretty much latest packages there are.</li>
  <li>Which variant should I pick? Minimal is command line with as little packages as possible, CLI is server install ready and desktop is XFCE.</li>
</ul>
</p>
