<p align="center">
  <a href="#">
  <img src="https://raw.githubusercontent.com/armbian/build/master/.github/armbian-logo.png" alt="Armbian logo" width="144">
  </a><br>
  <strong>Armbian Linux Community Supported Weekly Builds</strong><br>
<br>
<a href=https://github.com/armbian/community/actions/workflows/release.yml><img alt="GitHub Workflow Status" src="https://img.shields.io/github/workflow/status/armbian/community/Release?label=Automated%20Release&style=for-the-badge"></a>
<a href=https://github.com/armbian/community/actions/workflows/index.yml><img alt="GitHub Workflow Status" src="https://img.shields.io/github/workflow/status/armbian/community/Generating%20index?label=Indexing&style=for-the-badge"></a>
 <br>

<br>
<a href=https://twitter.com/armbian><img alt="Twitter Follow" src="https://img.shields.io/twitter/follow/armbian?logo=twitter&style=flat-square"></a>
<a href=http://discord.armbian.com/><img alt="Discord" src="https://img.shields.io/discord/854735915313659944?label=Discord&logo=discord&style=flat-square"></a>
<a href=https://liberapay.com/armbian><img alt="Liberapay patrons" src="https://img.shields.io/liberapay/patrons/armbian?logo=liberapay&style=flat-square"></a>
</p>
